version: '3'
services:
  db:
    image: postgres
    container_name: fudy-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: fudy-adminer
    restart: always
    ports:
      - 8080:8080
