services:
  db:
    image: postgres
    container_name: fudy-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: fudy-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
    name: 'fudy-data'
    labels:
      eu.fudy.project-name: 'Fudy'
      eu.fudy.description: 'Fudy data volume'
